### ISSUE TITLE
sending messages from discord doesnt send in game

### ISSUE THREAD

**Issue by BamsyTheSergal** [troit5ky/gmod_discord_relay#5]
sending a message in the gmod chat, that is working with everything else, just sending messages in the discord channel doesnt relay to the chat of gmod.

**Comment by troit5ky** [comment]
discord app (dev) > Bot > message content intent turn on
![Screenshot_20230423-224922_Chrome](https://user-images.githubusercontent.com/33691558/233861971-9cadfbb6-4706-4f69-952c-dfdd2226a1a1.png)

**Comment by BamsyTheSergal** [comment]
ah, i am dumb, i keep forgetting that, thank you!
